 /* AUTHENTICATION FIREBASE */
 export const FETCH_MOVIE_LIST_REQUEST = 'FETCH_MOVIE_LIST_REQUEST'
 export const FETCH_MOVIE_LIST_SUCCESS = 'FETCH_MOVIE_LIST_SUCCESS'
 export const FETCH_MOVIE_LIST_REJECT = 'FETCH_MOVIE_LIST_REJECT'
 export const SEARCH_MOVIE_WITH_NAME_SUCCESS = 'SEARCH_MOVIE_WITH_NAME_SUCCESS'