export const GET_LIST_PLANS = 'GET_LIST_PLANS'
export const ADD_MOVIE_PLAN_SUCCESS = 'ADD_MOVIE_PLAN_SUCCESS'
export const ADD_NEW_PLAN = 'ADD_NEW_PLAN'
export const DELETE_ALL_PLANS = 'DELETE_ALL_PLANS'